portal:
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - e:/Dev/docker-cluster/cluster/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - tomcatOne:tomcat1
   - tomcatTwo:tomcat2
   - tomcatThree:tomcat3
tomcatOne:
  image: tomcat:8.5
  volumes:
   - e:/Dev/docker-cluster/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - e:/Dev/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - e:/Dev/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
tomcatTwo:
  image: tomcat:8.5
  volumes:
   - e:/Dev/docker-cluster/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - e:/Dev/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - e:/Dev/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
tomcatThree:
  image: tomcat:8.5
  volumes:
   - e:/Dev/docker-cluster/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - e:/Dev/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - e:/Dev/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml


